### ISSUE TITLE
The problem with five gas giant planets

### ISSUE THREAD

**Issue by ghost** [YWMKerman/AfterSolarSystem#1]
The gas giant planet seems to have problems, and the region under the clouds can be seen
![$02I30 L{09)Z4AVL`YB_1G](https://user-images.githubusercontent.com/123361856/214021107-d8d5b2b2-6ae1-4738-ba8a-240ed83ed8d8.png)

**Comment by YWMKerman** [comment]
Yes, this BUG does exist, but I have solved and fixed this BUG under the current situation.
(I made it similar to reality for gaseous planets, where the altitude is 0 and the atmospheric pressure is 1atm, but using "Jool" as a template, your vehicle will explode at -250 meters. Therefore, I use "Eve" As a template, so it can dive deeper and reach -1638km.So the bug you see is caused by this, but now I have fixed this problem, you can't see this bug on the map. But it can still go down this deep)
